In [1]:
# Print the array

In [7]:
print(my_array)

NameError: name 'my_array' is not defined

In [8]:
#import 'numpy' as 'np'
import numpy as np

#Make the array "my array"
my_array = np.array([[1,2,3,4], [5,6,7,8]], dtype=np.int64)

#print 'my_array'
print(my_array)

[[1 2 3 4]
 [5 6 7 8]]


In [9]:
# Create an array of ones
np.ones((3,4))

# Create an array of zeros
np.zeros((2,3,4),dtype=np.int16)

# Create an array with random values
np.random.random((2,2))

# Create a empty array
np.empty((2,3))

#Create a full
np.full((2,2),7)

# Create an array of evenly spaced values
np.arange(10,25,5)

#Create an array of evenly space values again I guess
np.linspace(0,2,9)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [10]:

np.ones((3,4))



array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [11]:
np.zeros((2,3,4),dtype=np.int16)


array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int16)

In [12]:
np.random.random((2,2))



array([[ 0.96455416,  0.55128167],
       [ 0.95958537,  0.80206109]])

In [13]:
np.empty((2,3))



array([[  6.94887407e-310,   6.94887407e-310,   0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000]])

In [14]:
np.full((2,2),7)



array([[7, 7],
       [7, 7]])

In [15]:
np.arange(10,25,5)



array([10, 15, 20])

In [16]:
np.linspace(0,2,9)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [17]:
#arrary dimensions
print(my_array.ndim)

2


In [18]:
#number of array elemnts
print(my_array.size)

8


In [19]:
#my_array memory layout
print(my_array.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False


In [20]:
#length in bytes
print(my_array.itemsize)

8


In [21]:
#total consumed bytes by array
print(my_array.nbytes)

64


In [22]:
#length
print(len(my_array))

2


In [28]:
#change data type
my_array.astype(float)

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.]])

In [29]:
#initialize x
x = np.ones((3,4))

In [30]:
print(x.shape)

(3, 4)


In [31]:
y = np.random.random((3,4))

In [32]:
print(y.shape)

(3, 4)


In [33]:
x + y

array([[ 1.94746013,  1.10399136,  1.79057116,  1.0332722 ],
       [ 1.56781223,  1.3876972 ,  1.49916153,  1.56023883],
       [ 1.01380116,  1.5694118 ,  1.79878479,  1.05520334]])

In [34]:
x = np.ones((3,4))

In [35]:
print(x.shape)

(3, 4)


In [36]:
y = np.arange(4)

In [37]:
print(y.shape)

(4,)


In [38]:
x - y 

array([[ 1.,  0., -1., -2.],
       [ 1.,  0., -1., -2.],
       [ 1.,  0., -1., -2.]])

In [39]:
x = np.ones((3,4))

In [40]:
y = np.random.random((5,1,4))

In [41]:
x + y

array([[[ 1.59180601,  1.1305497 ,  1.30858182,  1.79913865],
        [ 1.59180601,  1.1305497 ,  1.30858182,  1.79913865],
        [ 1.59180601,  1.1305497 ,  1.30858182,  1.79913865]],

       [[ 1.81979537,  1.3608458 ,  1.67947459,  1.66331379],
        [ 1.81979537,  1.3608458 ,  1.67947459,  1.66331379],
        [ 1.81979537,  1.3608458 ,  1.67947459,  1.66331379]],

       [[ 1.91552471,  1.58937313,  1.00274847,  1.29566735],
        [ 1.91552471,  1.58937313,  1.00274847,  1.29566735],
        [ 1.91552471,  1.58937313,  1.00274847,  1.29566735]],

       [[ 1.31079303,  1.1319089 ,  1.83322093,  1.58877723],
        [ 1.31079303,  1.1319089 ,  1.83322093,  1.58877723],
        [ 1.31079303,  1.1319089 ,  1.83322093,  1.58877723]],

       [[ 1.09182863,  1.97568636,  1.93383   ,  1.60183992],
        [ 1.09182863,  1.97568636,  1.93383   ,  1.60183992],
        [ 1.09182863,  1.97568636,  1.93383   ,  1.60183992]]])

In [42]:
np.add(x,y)

array([[[ 1.59180601,  1.1305497 ,  1.30858182,  1.79913865],
        [ 1.59180601,  1.1305497 ,  1.30858182,  1.79913865],
        [ 1.59180601,  1.1305497 ,  1.30858182,  1.79913865]],

       [[ 1.81979537,  1.3608458 ,  1.67947459,  1.66331379],
        [ 1.81979537,  1.3608458 ,  1.67947459,  1.66331379],
        [ 1.81979537,  1.3608458 ,  1.67947459,  1.66331379]],

       [[ 1.91552471,  1.58937313,  1.00274847,  1.29566735],
        [ 1.91552471,  1.58937313,  1.00274847,  1.29566735],
        [ 1.91552471,  1.58937313,  1.00274847,  1.29566735]],

       [[ 1.31079303,  1.1319089 ,  1.83322093,  1.58877723],
        [ 1.31079303,  1.1319089 ,  1.83322093,  1.58877723],
        [ 1.31079303,  1.1319089 ,  1.83322093,  1.58877723]],

       [[ 1.09182863,  1.97568636,  1.93383   ,  1.60183992],
        [ 1.09182863,  1.97568636,  1.93383   ,  1.60183992],
        [ 1.09182863,  1.97568636,  1.93383   ,  1.60183992]]])

In [43]:
np.subtract(x,y)

array([[[ 0.40819399,  0.8694503 ,  0.69141818,  0.20086135],
        [ 0.40819399,  0.8694503 ,  0.69141818,  0.20086135],
        [ 0.40819399,  0.8694503 ,  0.69141818,  0.20086135]],

       [[ 0.18020463,  0.6391542 ,  0.32052541,  0.33668621],
        [ 0.18020463,  0.6391542 ,  0.32052541,  0.33668621],
        [ 0.18020463,  0.6391542 ,  0.32052541,  0.33668621]],

       [[ 0.08447529,  0.41062687,  0.99725153,  0.70433265],
        [ 0.08447529,  0.41062687,  0.99725153,  0.70433265],
        [ 0.08447529,  0.41062687,  0.99725153,  0.70433265]],

       [[ 0.68920697,  0.8680911 ,  0.16677907,  0.41122277],
        [ 0.68920697,  0.8680911 ,  0.16677907,  0.41122277],
        [ 0.68920697,  0.8680911 ,  0.16677907,  0.41122277]],

       [[ 0.90817137,  0.02431364,  0.06617   ,  0.39816008],
        [ 0.90817137,  0.02431364,  0.06617   ,  0.39816008],
        [ 0.90817137,  0.02431364,  0.06617   ,  0.39816008]]])

In [44]:

np.multiply(x,y)

array([[[ 0.59180601,  0.1305497 ,  0.30858182,  0.79913865],
        [ 0.59180601,  0.1305497 ,  0.30858182,  0.79913865],
        [ 0.59180601,  0.1305497 ,  0.30858182,  0.79913865]],

       [[ 0.81979537,  0.3608458 ,  0.67947459,  0.66331379],
        [ 0.81979537,  0.3608458 ,  0.67947459,  0.66331379],
        [ 0.81979537,  0.3608458 ,  0.67947459,  0.66331379]],

       [[ 0.91552471,  0.58937313,  0.00274847,  0.29566735],
        [ 0.91552471,  0.58937313,  0.00274847,  0.29566735],
        [ 0.91552471,  0.58937313,  0.00274847,  0.29566735]],

       [[ 0.31079303,  0.1319089 ,  0.83322093,  0.58877723],
        [ 0.31079303,  0.1319089 ,  0.83322093,  0.58877723],
        [ 0.31079303,  0.1319089 ,  0.83322093,  0.58877723]],

       [[ 0.09182863,  0.97568636,  0.93383   ,  0.60183992],
        [ 0.09182863,  0.97568636,  0.93383   ,  0.60183992],
        [ 0.09182863,  0.97568636,  0.93383   ,  0.60183992]]])

In [45]:
import numpy as np

In [46]:
np.divide(x,y)

array([[[   1.6897429 ,    7.65991778,    3.24063158,    1.25134731],
        [   1.6897429 ,    7.65991778,    3.24063158,    1.25134731],
        [   1.6897429 ,    7.65991778,    3.24063158,    1.25134731]],

       [[   1.2198166 ,    2.77126686,    1.47172537,    1.50758212],
        [   1.2198166 ,    2.77126686,    1.47172537,    1.50758212],
        [   1.2198166 ,    2.77126686,    1.47172537,    1.50758212]],

       [[   1.09226981,    1.696718  ,  363.83882241,    3.38217928],
        [   1.09226981,    1.696718  ,  363.83882241,    3.38217928],
        [   1.09226981,    1.696718  ,  363.83882241,    3.38217928]],

       [[   3.21757542,    7.58098956,    1.20016189,    1.69843526],
        [   3.21757542,    7.58098956,    1.20016189,    1.69843526],
        [   3.21757542,    7.58098956,    1.20016189,    1.69843526]],

       [[  10.88985033,    1.02491952,    1.07085872,    1.66157139],
        [  10.88985033,    1.02491952,    1.07085872,    1.66157139],
        [  1

In [47]:
np.remainder(x,y)

array([[[ 0.40819399,  0.08615207,  0.07425453,  0.20086135],
        [ 0.40819399,  0.08615207,  0.07425453,  0.20086135],
        [ 0.40819399,  0.08615207,  0.07425453,  0.20086135]],

       [[ 0.18020463,  0.27830841,  0.32052541,  0.33668621],
        [ 0.18020463,  0.27830841,  0.32052541,  0.33668621],
        [ 0.18020463,  0.27830841,  0.32052541,  0.33668621]],

       [[ 0.08447529,  0.41062687,  0.00230548,  0.11299794],
        [ 0.08447529,  0.41062687,  0.00230548,  0.11299794],
        [ 0.08447529,  0.41062687,  0.00230548,  0.11299794]],

       [[ 0.06762092,  0.07663769,  0.16677907,  0.41122277],
        [ 0.06762092,  0.07663769,  0.16677907,  0.41122277],
        [ 0.06762092,  0.07663769,  0.16677907,  0.41122277]],

       [[ 0.08171373,  0.02431364,  0.06617   ,  0.39816008],
        [ 0.08171373,  0.02431364,  0.06617   ,  0.39816008],
        [ 0.08171373,  0.02431364,  0.06617   ,  0.39816008]]])

In [48]:
np.logical_and(a, b)

NameError: name 'a' is not defined

In [49]:
np.logical_or(a, b)

NameError: name 'a' is not defined

In [50]:
np.logical_not(a, b)

NameError: name 'a' is not defined

In [51]:
print(my_array)

[[1 2 3 4]
 [5 6 7 8]]


In [54]:
print(x)


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
